server:
  port: 9002

spring:
  application:
    name: xdclass-coupon-service
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdclass_coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #  redis配置
  redis:
    host: 8.129.113.233
    port: 8000
    password: 123456

# 配置 plus 打印 sql ⽇志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置⽇志级别,ERROR/WARN/INFO/DEBUG,默认是 INFO 以上才显示
logging:
  level:
    root: INFO

