server:
  port: 9001

spring:
  application:
    name: xdclass-user-service
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdclass_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #  redis配置
  redis:
    host: 127.0.0.1
    port: 8000
    password: 123456
    #邮箱服务配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: sunshine3468@163.com #发送邮件的邮箱地址
    password: GE9gw395HfdqXFhB #客户端授权码，不是邮箱密码,⽹易的是⾃⼰设置的
    from: sunshine3468@163.com # 发送邮件的地址，和上⾯username⼀致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
# 配置 plus 打印 sql ⽇志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置⽇志级别,ERROR/WARN/INFO/DEBUG,默认是 INFO 以上才显示
logging:
  level:
    root: INFO

